version: "1"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vikasfse
    networks:
      springboot-mysql-net:

  fseb:
      container_name: fseb
      build:
        context: ./fullstack-backend-master
        dockerfile: Dockerfile
      ports:
        - "8080:8080"
      depends_on:
        - mysqldb
      networks:
        springboot-mysql-net:
      restart: on-failure

