version: "3"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vikasfse
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - fse-db:/var/lib/mysql
    networks:
      - fse-net

  fseb:
      container_name: fseb1
      build:
        dockerfile: Dockerfile
      ports:
        - "8080:8080"
      depends_on:
        - mysqldb
      networks:
        - fse-net
     # restart: on-failure

#create a network
networks:
  fse-net:

#create a volume
volumes:
  fse-db:


